### ISSUE TITLE
Feedback for Documentation

### ISSUE THREAD

**Issue by kunaltyagi** [arzoo14/PCL_coding_work_2#1]
**Achievements**
* Sphinx integration with readthedocs
* Integration with `rst` for tutorials

**Missing**
* PCL is heavily based on Doxygen, and without a working bridge between Doxygen and Sphinx, it'll be hard to get one-single source of documentation
* CMake integration: PCL relies heavily on CMake, using Makefiles will be problematic in long run
* Version support: 1.9.1, 1.10.1, 1.11, etc. should be clearly available.

This is not an authoritative feedback, just what I felt is missing. Other maintainers of PCL will be able to provide better feedback

**Comment by arzoo14** [comment]
-  Doxygen will be integrated with the help of doxylinks in sphinx.
- Will use breathe in addition to sphinx for CMake.

**Comment by arzoo14** [comment]
Closing this issue as these all are completed and mentioned in the proposal.
