### ISSUE TITLE
Found additional ads

### ISSUE THREAD

**Issue by wz18207** [arzoo14/PCL_coding_work_2#3]
Thanks for arrangement. This website look nice.
However, I found the additional ad on this website.

Browser: chrome-stable_x64:81.0.4044.92
Here are the photos:

![2](https://user-images.githubusercontent.com/47554726/79595092-d4ed4200-8110-11ea-801d-ca5ecaa4e53a.png)

when I am trying to check the details of this website's loading, I found this strange url:
![1](https://user-images.githubusercontent.com/47554726/79595248-14b42980-8111-11ea-8a5e-059c8d3f1c4a.png)

The random address directed behind this unfamiliar website may be directed to an unfamiliar advertising page, which is seems to be a worried question.
 Could you let these ads invade here? Thanks so much!

**Comment by arzoo14** [comment]
This additional ad is provided by ReadTheDocs.
It can be removed using several methods.
Please have a look - https://docs.readthedocs.io/en/latest/advertising/ethical-advertising.html#opting-out
